### ISSUE TITLE
New release without camlp4

### ISSUE THREAD

**Issue by XVilka** [Chris00/integration1d#1]
Camlp4 release for OCaml 4.08 is the last release ever - see the [official announcement](https://discuss.ocaml.org/t/the-end-of-camlp4/4216). Since the project already dropped camlp4 dependency it would be good to make the release for opam as well: http://opam.ocaml.org/packages/integration1d

**Comment by Chris00** [comment]
I'll try to make a new release ASAP — I'll have to see whether I have time to finish an additional function (probably not).
